USE MASTER
GO
CREATE DATABASE BDGestaoSala
GO
USE BDGestaoSala
GO
CREATE TABLE Sala(
SalaID INT IDENTITY (1,1) PRIMARY KEY,
SalaDESCRICAO VARCHAR (50) NOT NULL,
)
GO
CREATE TABLE Ocupacao (
OcupID INT IDENTITY (1,1) PRIMARY KEY,
SalaID INT NOT NULL,
OcupDATA DATETIME NOT NULL,
OcupHoraInicio DATETIME NOT NULL,
OcupHoraFim DATETIME NULL
 CONSTRAINT FK_SALAOCUPACAO FOREIGN KEY (SalaID)
 REFERENCES Sala(SalaID)
)
